Cut Some Code On The Wild Side
==============================
Barry Arthur
v1.1, May 10, 2011

_(apologies to Lou Reed)_

Thanks to Belinda Allan and Timo Schmiade for assistance with the
lyrics.

[verse]
______________________________________________________________________________
Johnny came from a small dev shop,
Used only tools from Microsoft,
Tried out Ruby on a whim,
Tossed C# and installed Vim; he said

Hey, mate, cut some code on the wild side
Said hey buddy, cut some code on the wild side

Timothy only knew C
Never knew he didn't need free()
Leaves his objects for gc
Now that he codes in Ruby; he says

Hey, mate, cut some code on the wild side
Said hey buddy, cut some code on the wild side
And Ruby coders can do do do-do-do do

Sarah thought she was doing fine
Writing Java all of the time
Watched a colleague finish a task
Did it in ruby twice as fast; he said

Hey, babe, cut some code on the wild side
Said hey honey, cut some code on the wild side

Jim using Python thought he was cool
But There's Only One Way to use that tool
Ruby likes to do it different ways
She lets you choose how you play; she says

Hey, babe, cut some code on the wild side
Said hey buddy, cut some code on the wild side

Phil built his sites in PHP
"Ain't gonna change, I'm old-skool, me."
Saw a railscast and said, "No way!"
Now he uses rails to earn his pay; he says

Hey, mate, cut some code on the wild side
Said hey buddy, cut some code on the wild side
And Ruby coders can do do do-do-do do

Peter spent every night with Perl
He thought of her as his girl
Ruby caught his eye one day
Seduced him to her Way; she said

Hey, babe, cut some code on the wild side
Said hey honey, cut some code on the wild side

Old man Doug was a whiz at lisp
He knew it like noone's biz
Ruby's closures are so fine
But lisp's had that since '59; he said

Hey, pup, cut some code on the wild side
Said hey sonny, cut some code on the wild side

Been using Ruby for quite a while
She warms my heart and makes me smile
But try as I might, much as I've plead
Just can't get her to warm my bed; she says

Hey, man, spend some time on the wild side
Said hey honey, take a girl on a wild ride
And I just might do do do-do-do do

I just might *do* that..

do do do-do-do do
______________________________________________________________________________

