Cut Some Code On The Wild Side
==============================
Barry Arthur
v1.1, May 10, 2011

_(apologies to Lou Reed)_

Thanks to Belinda Allan and Timo Schmiade for assistance with the
lyrics.

[verse]
______________________________________________________________________________
**Jo**hnny came *from* a *small* dev *shop*,
*Used* only *tools* from **Mi**cro**soft**,
*Tried* out **Ru**by *on* a *whim*,
*Tossed* C**#** and **in**stalled *Vim*; he said

Hey, mate, cut some code on the wild side
Said hey buddy, cut some code on the wild side

**Ti**mo**thy** **on**ly knew *C*
**Ne**ver *knew* he **di**dn't need *free()*
*Leaves* his **ob**jects *for* g**c**
*Now* that he *codes* *in* Ru**by**; he says

Hey, mate, cut some code on the wild side
Said hey buddy, cut some code on the wild side
And Ruby coders can do do do-do-do do

**Sa**rah *thought* *she* was doing *fine*
**Wri**ting **Ja**va *all* of the *time*
**Wa**tched a **co**lleague **fi**nish a *task*
*Did* it in **ru**by *twice* as *fast*; he said

Hey, babe, cut some code on the wild side
Said hey honey, cut some code on the wild side

*Jim* using **Py**thon *thought* he was *cool*
But There's *Only* One *Way* to *use* that *tool*
**Ru**by likes to *do* it **di**fferent *ways*
She *lets* you *choose* *how* you *play*; she says

Hey, babe, cut some code on the wild side
Said hey buddy, cut some code on the wild side

*Phil* built his *sites* in **P**H**P**
"*Ain't* gonna *change*, I'm **old**-skool, *me*."
*Saw* a rails**cast** and *said*, "No *way*!"
*Now* he uses *rails* to *earn* his *pay*; he says

Hey, mate, cut some code on the wild side
Said hey buddy, cut some code on the wild side
And Ruby coders can do do do-do-do do

**Pe**ter **spent** every *night* with *Perl*
He *thought* of *her* *as* his *girl*
**Ru**by *caught* his *eye* one *day*
**Se**duced *him* *to* her *Way*; she said

Hey, babe, cut some code on the wild side
Said hey honey, cut some code on the wild side

*Old* man *Doug* was a *whiz* at *lisp*
He *knew* it *like* **no**one's *biz*
**Ru**by's **clo**sures *are* so *fine*
But **lisp's** had *that* since **'59**; he said

Hey, pup, cut some code on the wild side
Said hey sonny, cut some code on the wild side

Been **u**sing **Ru**by for *quite* a *while*
She *warms* my *heart* and *makes* me *smile*
But *try* as I *might*, *much* as I've *plead*
*Just* can't *get* her to *warm* my *bed*; she says

Hey, man, spend some time on the wild side
Said hey honey, take a girl on a wild ride
And I just might do do do-do-do do

I just might *do* that..

do do do-do-do do
______________________________________________________________________________

